[project]
name = "pdf-image-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdf2image>=1.17.0",
    "pypdf2>=3.0.1",
    "tk>=0.1.0",
]
